@component('dashboard::layouts.components.sidebarItem')
    @slot('url', route('dashboard.home'))
    @slot('name', trans('dashboard::dashboard.home'))
    @slot('icon', 'fas fa-tachometer-alt')
    @slot('routeActive', 'dashboard.home')
@endcomponent
@include('countries::sidebar')
@include('accounts::sidebar')
@include('stores::sidebar')
@include('subscriptions::sidebar')
@include('categories::sidebar')
@include('custom_fields::sidebar')
@include('custom_field_options::sidebar')
@include('products::sidebar')
@include('orders::sidebar')
@include('coupons::sidebar')
@include('coupon_products::sidebar')
@include('order_products::sidebar')
@include('order_statuses::sidebar')
@include('offers::sidebar')

